apiVersion: batch/v1
kind: Job
metadata:
  name: "portway-db-job"
  labels:
    app.kubernetes.io/managed-by: "portway"
spec:
  template:
    metadata:
      name: "portway-db-job"
      labels:
        app.kubernetes.io/managed-by: "portway"
    spec:
      restartPolicy: Never
      imagePullSecrets:
      - name: regcred
      containers:
      - name: portway-db
        image: "bonkeybong/portway_db_jobs:master-31969aa"
        args: ["setDeletedRecords"]
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: api.db-host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: api.db-name
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: api.db-port
        - name: DB_USE_SSL
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: api.db-use-ssl
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: api.db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db_user_password