apiVersion: batch/v1
kind: Job
metadata:
  name: "portway-db-job"
  labels:
    app.kubernetes.io/managed-by: "portway"
spec:
  template:
    metadata:
      name: "portway-db-job"
      labels:
        app.kubernetes.io/managed-by: "portway"
    spec:
      restartPolicy: Never
      imagePullSecrets:
      - name: regcred
      containers:
      - name: portway-db
        image: "bonkeybong/portway_db_jobs:main-31969aa"
        args: ["setDeletedRecords"]
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: api.db-host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: api.db-name
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: api.db-port
        - name: DB_USE_SSL
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: api.db-use-ssl
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: api.db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db_user_password
        - name: AWS_SES_REGION
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: api.aws-ses-region
        - name: S3_CONTENT_BUCKET
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: api.s3-content-bucket
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: secret_access_key
        - name: ADMIN_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: admin-secrets
              key: admin_secret_key
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: web-config
              key: web.api_url
