apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: portway-remove-unverified-org-cronjob
spec:
  schedule: "0 10 * * *"
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
          - name: regcred
          restartPolicy: OnFailure
          containers:
          - name: portway-remove-unverified-org
            image: bonkeybong/portway_remove_unverified_org
            env:
            - name: ADMIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: admin-secrets
                  key: admin_secret_key
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: web-config
                  key: web.api_url
