version: '3'

services:

  web:
    platform: linux/x86_64
    build:
      context: ./web
    volumes:
      - ./web:/web
      - /web/node_modules
    working_dir: /web
    command: devstart
    ports:
      - 3000:3000
    env_file:
      - ./web/src/server/.env
    environment:
      NODE_ENV: development
    container_name: portway-web

  api:
    platform: linux/x86_64
    build:
      context: ./api
    volumes:
      - ./api:/api
      - /api/node_modules
    working_dir: /api
    entrypoint: /bin/sh
    command: ./wait-for.sh db:5432 -- ./run.sh devstart
    ports:
      - 3001:3001
    env_file:
      - ./api/.env
    environment:
      NODE_ENV: development
      API_PORT: 3001
    depends_on:
      - db
    container_name: portway-api

  sync:
    platform: linux/x86_64
    build:
      context: ./sync
    volumes:
      - ./sync:/sync
      - /sync/node_modules
    working_dir: /sync
    entrypoint: /bin/sh
    command: ./wait-for.sh redis:6379 -- ./run.sh devstart
    ports:
      - 3004:3004
    env_file:
      - ./sync/.env
    environment:
      NODE_ENV: development
      SYNC_PORT: 3004
    depends_on:
      - redis
    container_name: portway-sync

  workers:
    platform: linux/x86_64
    build:
      context: ./workers
    volumes:
      - ./workers:/workers
      - /workers/node_modules
    working_dir: /workers
    entrypoint: /bin/sh
    command: ./wait-for.sh redis:6379 -- ./run.sh devstart
    env_file:
      - ./workers/.env
    environment:
      NODE_ENV: development
    depends_on:
      - redis
    container_name: portway-worker

  db:
    platform: linux/x86_64
    image: postgres:11.2-alpine
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: bonkey
      POSTGRES_PASSWORD: bong
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    platform: linux/x86_64
    image: redis:5.0.7-alpine
    ports:
      - 6379:6379

volumes:
  postgres-data:

