version: "3"

services:
  api-testrunner:
    build:
      context: ./api
    volumes:
      - ./api:/api
      - /api/node_modules
    working_dir: /api
    command: test
    environment:
      NODE_ENV: test
      API_PORT: 3001
      DB_HOST: 'db-test'
      DB_PORT: 5432
      DB_USER: 'bonkey'
      DB_PASSWORD: 'bong'
      DB_NAME: 'test'
    depends_on:
      - db-test
    tty: true

  db-test:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: bonkey
      POSTGRES_PASSWORD: bong
    ports:
      - 5432:5432
