version: '3'

services:

  web:
    build:
      context: ./web
      dockerfile: Dockerfile-dev
    volumes:
      - ./web:/web
      - /web/node_modules
    working_dir: /web
    command: devstart
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development

  api:
    build:
      context: ./api
      dockerfile: Dockerfile-dev
    volumes:
      - ./api:/api
      - /api/node_modules
    working_dir: /api
    entrypoint: /bin/sh
    command: ./wait-for.sh db:5432 -- npm run serve
    ports:
      - 3001:3001
    environment:
      NODE_ENV: development
      API_PORT: 3001
    depends_on:
      - "db"

  db:
    image: postgres:11.2-alpine
    restart: always
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: bonkey
      POSTGRES_PASSWORD: bong
    volumes:
      - database_data:/var/lib/postgresql/dev_db
    ports:
      - "5432:5432"

volumes:
  database_data:
    driver: local