version: '3'

services:

  web:
    build:
      context: ./web
      dockerfile: Dockerfile-dev
    volumes:
      - ./web:/web
      - /web/node_modules
    working_dir: /web
    command: devstart
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development

  api:
    build:
      context: ./api
      dockerfile: Dockerfile-dev
    volumes:
      - ./api:/api
      - /api/node_modules
    working_dir: /api
    command: devstart
    ports:
      - 3001:3001
    environment:
      NODE_ENV: development
      API_PORT: 3001

  db:
    image: postgres:11.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: bonkey
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local