version: "3"

services:
  api-testrunner:
    build:
      context: ./api
      dockerfile: Dockerfile-dev
    volumes:
      - ./api:/api
      - /api/node_modules
    working_dir: /api
    command: test
    environment:
      NODE_ENV: test
      API_PORT: 3001

    depends_on:
      - db-test

  db-test:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: bonkey
      POSTGRES_PASSWORD: bong
    ports:
      - 5432:5432
