version: '3'

services:

  web:
    image: node:10.15.1
    volumes:
      - ./web:/usr/src/service/web
    working_dir: /usr/src/service/web
    command: npm run serve
    ports:
      - 3000:3000
      - 1235:1235
    environment:
      NODE_ENV: development

  api:
    image: node:10.15.1
    volumes:
      - ./api:/usr/src/service/api
    working_dir: /usr/src/service/api
    command: npm run serve
    ports:
      - 3001:3001
    environment:
      NODE_ENV: development
