version: '3'

services:

  web:
    build:
      context: ./web
    volumes:
      - ./web:/web
      - /web/node_modules
    working_dir: /web
    command: devstart
    ports:
      - 3000:3000
    env_file:
      - ./web/src/server/.env
    environment:
      NODE_ENV: development
    container_name: danger-web

  api:
    build:
      context: ./api
    volumes:
      - ./api:/api
      - /api/node_modules
    working_dir: /api
    entrypoint: /bin/sh
    command: ./wait-for.sh db:5432 -- ./run.sh devstart
    ports:
      - 3001:3001
    env_file:
      - ./api/.env
    environment:
      NODE_ENV: development
      API_PORT: 3001
    depends_on:
      - db
    container_name: danger-api

  db:
    image: postgres:11.2-alpine
    restart: always
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: bonkey
      POSTGRES_PASSWORD: bong
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres-data: