version: '2'

services:

  web:
    image: node:10.15.1
    volumes:
      - ./web:/usr/src/service/web
    working_dir: /usr/src/service/web

  api:
    image: node:10.15.1
    volumes:
      - ./api:/usr/src/service/api
    working_dir: /usr/src/service/api

  install_web:
    extends:
      service: web
    command: npm install

  install_api:
    extends:
      service: api
    command: npm install

  build_web:
    extends:
      service: web
    command: npm run build

  build_api:
    extends:
      service: api
    command: npm run build

  create-bundles_web:
    extends:
      service: web
    command: npm run create-bundles

  create-bundles_api:
    extends:
      service: api
    command: npm run create-bundles
