---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        run: api
        app: api
    spec:
      containers:
      - image: bonkeybong/portway_api
        imagePullPolicy: "Never"
        name: api
        args: [ "start"  ]
        env:
        - name: API_PORT
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: api.port
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: api.db-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: api.db-port
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: api.db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db_user_password
        - name: AWS_SES_REGION
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: api.aws-ses-region
        - name: SENDER_EMAIL_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: api.sender-email-address
        - name: CLIENT_URL
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: api.client-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: token-secrets
              key: jwt_secret
        - name: PASSWORD_RESET_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: token-secrets
              key: password_reset
        - name: STRIPE_SECRET
          valueFrom:
            secretKeyRef:
              name: stripe-secrets
              key: secret
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: secret_access_key
        ports:
        - containerPort: 3001
          protocol: TCP
