---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        run: api
        app: api
    spec:
      containers:
      - image: portway/api
        imagePullPolicy: "Never"
        name: api
        args: [ "start"  ]
        env:
        - name: API_PORT
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: api.port
        ports:
        - containerPort: 3001
          protocol: TCP
