---
apiVersion: v1
items:
- apiVersion: v1
  data:
    api.port: "3001"
    api.db-host: "dev-db-portway-do-user-2269753-0.db.ondigitalocean.com"
    api.db-port: "25060"
    api.db-user: "doadmin"
    api.db-name: "defaultdb"
    api.db-use-ssl: "true"
    api.aws-ses-region: "us-west-2"
    api.sender-email-address: "no-reply@portway.app"
    api.client-url: "http://dev.portway.app"
    api.s3-content-bucket: 'portway-content-dev'
  kind: ConfigMap
  metadata:
    name: api-config
    namespace: default
- apiVersion: v1
  data:
    web.static_port: "3000"
    web.api_url: "http://api:3001"
    web.api_public_url: "http://api.dev.portway.app"
  kind: ConfigMap
  metadata:
    name: web-config
    namespace: default
kind: List
