apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: portway-ingress
  annotations:  
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - dev.portway.app
    - api.dev.portway.app
    secretName: letsencrypt-prod
  rules:
  - host: api.dev.portway.app
    http:
      paths:
      - backend:
          serviceName: api-service
          servicePort: 3001
  - host: dev.portway.app
    http:
      paths:
      - backend:
          serviceName: web-service
          servicePort: 3000