version: '1.0'
mode: parallel
stages:
  - Clone Repo
  - Web
  - API
steps:
  main_clone:
    title: Cloning main repository...
    stage: Clone Repo
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
  build_prod_api_image:
    stage: API
    title: Building API Production Image
    type: build
    image_name: bonkeybong/portway_api
    working_directory: ./api/
    tag: '${{CF_RELEASE_TAG}}'
    dockerfile: Dockerfile-prod
    when:
      steps:
        - name: main_clone
          on:
            - success
  build_prod_web_image:
    stage: Web
    title: Building Web Production Image
    type: build
    image_name: bonkeybong/portway_web
    working_directory: ./web/
    tag: '${{CF_RELEASE_TAG}}'
    dockerfile: Dockerfile-prod
    when:
      steps:
        - name: main_clone
          on:
            - success
  push_web_to_registry:
    stage: Web
    type: push
    title: Push Web to Docker Registry
    candidate: ${{build_prod_web_image}}
    tag: '${{CF_RELEASE_TAG}}'
    image_name: bonkeybong/portway_web
    registry: bonkeybong
    when:
      steps:
        - name: build_prod_web_image
          on:
            - success
  push_api_to_registry:
    stage: API
    type: push
    title: Push API to Docker Registry
    candidate: ${{build_prod_api_image}}
    tag: '${{CF_RELEASE_TAG}}'
    image_name: bonkeybong/portway_api
    registry: bonkeybong
    when:
      steps:
        - name: build_prod_api_image
          on:
            - success