---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-service
spec:
  selector:
    app: {{ .Values.serviceNames.api }}
  ports:
  - protocol: TCP
    port: {{ .Values.api.port }}
    targetPort: {{ .Values.api.port }}