apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: portway-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # This metadata controls which letsencrypt provider, staging or prod
    cert-manager.io/issuer: {{ .Values.certIssuer }}
spec:
  tls:
  - hosts:
    - {{ .Values.baseUrl }}
    - {{ .Values.apiPublicUrl }}
    - {{ .Values.docsUrl }}
    - {{ .Values.syncUrl }}
    secretName: {{ .Values.certIssuer }}-cert
  rules:
  - host: {{ .Values.apiPublicUrl }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-api-service
          servicePort: {{ .Values.api.port }}
  - host: {{ .Values.baseUrl }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-web-service
          servicePort: {{ .Values.web.port }}
  - host: {{ .Values.docsUrl }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-docs-service
          servicePort: {{ .Values.docs.port }}
  - host: {{ .Values.syncUrl }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-sync-service
          servicePort: {{ .Values.sync.port }}
---
apiVersion: v1
data:
  proxy-body-size: "100M"
kind: ConfigMap
metadata:
  name: nginx-configuration