apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: portway-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: {{ .Values.certName }}
spec:
  tls:
  - hosts:
    - {{ .Values.baseUrl }}
    - {{ .Values.apiPublicUrl }}
    secretName: {{ .Values.certName }}
  rules:
  - host: {{ .Values.apiPublicUrl }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-api-service
          servicePort: 3001
  - host: {{ .Values.baseUrl }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-web-service
          servicePort: 3000