---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: {{ .Values.serviceNames.redis }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.serviceNames.redis }}
  template:
    metadata:
      labels:
        run: redis
        app: {{ .Values.serviceNames.redis }}
    spec:
      containers:
      - image: redis:5.0-alpine
        name: {{ .Values.serviceNames.redis }}
        ports:
        - containerPort: {{ .Values.redis.port }}
          protocol: TCP