---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sync-service
spec:
  selector:
    app: {{ .Values.serviceNames.sync }}
  ports:
  - protocol: TCP
    port: {{ .Values.sync.port }}
    targetPort: {{ .Values.sync.port }}