---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-service
spec:
  selector:
    app: web
  ports:
  - protocol: TCP
    port: {{ .Values.web.port }}
    targetPort: {{ .Values.web.port }}
