---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-workers-service
spec:
  selector:
    app: {{ .Values.serviceNames.workers }}
  ports:
  - protocol: TCP
    port: {{ .Values.workers.port }}
    targetPort: {{ .Values.workers.port }}